version: '3.8'

services:
  db:
    image: postgres:12.20
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080